import os

DATA_PATH = "data/reviews.csv"
TEXT_COL = "text"
LABEL_COL = "rating"
RANDOM_STATE = 42
TEST_SIZE = 0.2

LEMMATIZE = True
CACHE_SIZE = 200_000

TFIDF_WORD_MAX_FEATURES = 100_000
TFIDF_WORD_NGRAM_RANGE = (1, 3)
TFIDF_WORD_MIN_DF = 2

TFIDF_CHAR_MAX_FEATURES = 50_000
TFIDF_CHAR_NGRAM_RANGE = (2, 5)
TFIDF_CHAR_MIN_DF = 3

RIDGE_ALPHA = 1.0

SVD_N_COMPONENTS = 200

CB_ITERATIONS = 2000
CB_LEARNING_RATE = 0.05
CB_DEPTH = 6
CB_LOSS = "RMSE"
CB_EVAL_METRIC = "RMSE"

ENSEMBLE_WEIGHT_RIDGE = 0.5
ENSEMBLE_WEIGHT_CATBOOST = 0.5

os.makedirs("models", exist_ok=True)
TFIDF_RIDGE_PATH = "models/tfidf_ridge.pkl"
CATBOOST_MODEL_PATH = "models/catboost_model"
CATBOOST_EXTR_PATH = "models/catboost_extractor.pkl"